/* Auto-generated by AuthSystem - 2026-05-07T02:28:54.810Z */
// Public configuration for auth forms
// These values are embedded at build time
// The forms call the public API (Netlify Functions), not Supabase directly

export const config = {
  apiBaseUrl: '/api', // Uses Netlify redirect from netlify.toml
  appId: 'app_027dc910-c75',
  apiKey: 'ak_development_46498fd4fda6d8a5228e996307beaa2d'
};
